'use server'

import { createClient } from '@/lib/supabase/server'
import { createReportPDF } from '@/lib/pdf-helper'

export async function exportParticipantsCSV(eventId: string) {
    const supabase = await createClient()

    // Auth Check
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { error: 'Unauthorized' }

    // Fetch Data
    const { data: registrations } = await supabase
        .from('registrations')
        .select(`
            status,
            user:profiles!user_id(full_name, email),
            event:events(title),
            created_at
        `)
        .eq('event_id', eventId)

    if (!registrations) return { error: 'No data found' }

    // Log Action
    await supabase.from('audit_logs').insert({
        actor_id: user.id,
        action: 'EXPORT_REPORT',
        entity_type: 'events',
        entity_id: eventId,
        new_values: { type: 'participants_csv' }
    })

    // Generate CSV
    const headers = ['Name', 'Email', 'Status', 'Registered At']
    interface RegistrationWithDetails {
        status: string;
        created_at: string;
        user: { full_name: string; email: string };
        event: { title: string; date: string };
    }

    // Cast to expected type since Supabase query types are loose here
    const typedRegistrations = registrations as unknown as RegistrationWithDetails[]

    const rows = typedRegistrations.map(reg => [
        reg.user?.full_name || 'N/A',
        reg.user?.email || 'N/A',
        reg.status,
        new Date(reg.created_at).toLocaleString()
    ])

    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
    return { success: true, data: csvContent, filename: `participants-${eventId}.csv` }
}

export async function exportParticipantsPDF(eventId: string) {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { error: 'Unauthorized' }

    const { data: registrations } = await supabase
        .from('registrations')
        .select(`
            status,
            user:profiles!user_id(full_name, email),
            event:events(title, date),
            created_at
        `)
        .eq('event_id', eventId)

    if (!registrations || registrations.length === 0) return { error: 'No data found' }

    await supabase.from('audit_logs').insert({
        actor_id: user.id,
        action: 'EXPORT_REPORT',
        entity_type: 'events',
        entity_id: eventId,
        new_values: { type: 'participants_pdf' }
    })

    interface RegistrationWithDetails {
        status: string;
        user: { full_name: string; email: string };
        event: { title: string; date: string };
    }
    const typedRegistrations = registrations as unknown as RegistrationWithDetails[]

    const event = typedRegistrations[0].event
    const pdfBuffer = await createReportPDF(
        'Participants List',
        [
            `Event: ${event?.title || 'Unknown Event'}`,
            `Date: ${event?.date ? new Date(event.date).toLocaleDateString() : 'N/A'}`,
            `Generated By: ${user.email}`,
            `Total: ${registrations.length}`
        ],
        [
            { header: 'Name', width: 150, field: 'name' },
            { header: 'Email', width: 200, field: 'email' },
            { header: 'Status', width: 100, field: 'status' }
        ],
        typedRegistrations.map(r => ({
            name: r.user?.full_name || 'N/A',
            email: r.user?.email || 'N/A',
            status: r.status
        }))
    )

    // Return Base64 for client download
    return {
        success: true,
        data: pdfBuffer.toString('base64'),
        filename: `participants-${eventId}.pdf`
    }
}
